name: json_repo
description: ...
version: 0.0.1
homepage: https://github.com/code-red-panda/flutter_json_repo

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  very_good_analysis: 5.1.0 # https://pub.dev/packages/very_good_analysis/install